// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgpIJcGNXEc9jVqqwf0sApOxi_QZAHOZc',
    appId: '1:517022631948:web:5220e2ceae22806b1bc629',
    messagingSenderId: '517022631948',
    projectId: 'todo-app-flutter-70026',
    authDomain: 'todo-app-flutter-70026.firebaseapp.com',
    storageBucket: 'todo-app-flutter-70026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOmXcBwXC4wgW7q4x4WP87jnKDY7pldx0',
    appId: '1:517022631948:android:12a448e42c9b16e11bc629',
    messagingSenderId: '517022631948',
    projectId: 'todo-app-flutter-70026',
    storageBucket: 'todo-app-flutter-70026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6K9ibkCFt278Oh7tKylY7ib2-DN5pGFs',
    appId: '1:517022631948:ios:65d3c97bd15962351bc629',
    messagingSenderId: '517022631948',
    projectId: 'todo-app-flutter-70026',
    storageBucket: 'todo-app-flutter-70026.firebasestorage.app',
    iosBundleId: 'com.example.ykosKitchen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6K9ibkCFt278Oh7tKylY7ib2-DN5pGFs',
    appId: '1:517022631948:ios:65d3c97bd15962351bc629',
    messagingSenderId: '517022631948',
    projectId: 'todo-app-flutter-70026',
    storageBucket: 'todo-app-flutter-70026.firebasestorage.app',
    iosBundleId: 'com.example.ykosKitchen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgpIJcGNXEc9jVqqwf0sApOxi_QZAHOZc',
    appId: '1:517022631948:web:b2db835912906f431bc629',
    messagingSenderId: '517022631948',
    projectId: 'todo-app-flutter-70026',
    authDomain: 'todo-app-flutter-70026.firebaseapp.com',
    storageBucket: 'todo-app-flutter-70026.firebasestorage.app',
  );
}
